include:
- buildah/dukkha.yaml
- golang/dukkha.yaml
- linter/dukkha.yaml

global:
  values:
    cmd:
      run_container@file|template: templates/cmd-run-container.yml

tools:
  workflow:
  - name: local

renderers:
  env:
    enable_exec: true

workflow:run:
- name: test
  matrix:
    preset:
    - golang
    - buildah
    - linter
  jobs:
  - task@template: workflow:run(test-{{ matrix.preset }}, {})

- name: tidy
- name: lint
  matrix:
    include:
    - linter: [editorconfig-checker]
      # version: ["2.3"]
      # workdir: [""]
      # config: [".ecrc"]

    # TODO
    - linter: [shellcheck]
      # version: [""]
      # workdir: [""]

    - linter: [yamllint]
      # version: ["1.26"]
      # workdir: [""]
      # config: [".yaml-lint.yml"]

    - linter: [golangci-lint]
      # version: ["1.43"]
      # workdir: [""]
      # config: [""]
      # pkgs: ["./..."]

      workdir@template: |-
        - {{ filepath.Join env.DUKKHA_WORKING_DIR "golang/testdata" -}}
      config: ["../../linter/testdata/golangci-lint.yml"]

  jobs:
  - shell@template|file|template: |-
      linter/{{- matrix.linter -}}.tpl
    env:
    - name@template: |-
        {{- matrix.linter | strings.SnakeCase | strings.ToUpper -}}
      value@template: |-
        {{- matrix.version | default "" -}}
