include:
- buildah/dukkha.yaml
- golang/dukkha.yaml

tools:
  workflow:
  - name: local

renderers:
  env:
    enable_exec: true

workflow:run:
- name: test
  matrix:
    preset:
    - golang
    - buildah
  jobs:
  - task@template: workflow:run(test-{{ matrix.preset }}, {})
