include:
- buildah/test.yaml
- golang/test.yaml
- tools/test.yaml

global:
  values:
    cmd:
      run_ctr@file|tpl: templates/run-ctr.yml

tools:
  workflow:
  - name: local

renderers:
- env:
    enable_exec: true

workflow:run:
- name: test
  matrix:
    preset:
    - golang
    - buildah
    - tools
  jobs:
  - task@tpl: workflow:run(test-{{ matrix.preset }}, {})

- name: report
- name: tidy
- name: lint
  matrix:
    include:
    - tool: [editorconfig-checker]
      # version: ["2.3"]
      # workdir: [""]
      # config: [".ecrc"]

    # TODO
    - tool: [shellcheck]
      # version: [""]
      # workdir: [""]

    - tool: [yamllint]
      # version: ["1.26"]
      # workdir: [""]
      # config: [".yaml-lint.yml"]

    - tool: [golangci-lint]
      # version: ["1.43"]
      # workdir: [""]
      # config: [""]
      # pkgs: ["./..."]

      workdir@tpl: |-
        - {{ filepath.Join dukkha.WorkDir "golang/testdata" -}}
      config: ["../../tools/testdata/golangci-lint.yml"]

  jobs:
  - cmd@file|tpl#use-spec: tools/file.tpl
    chdir@tpl: |-
      {{- matrix.workdir | default "" -}}
