include:
- path: buildah/test.yaml
- path: golang/test.yaml
- path: tools/test.yaml

global:
  values:
    cmd:
      run_ctr@tpl#use-spec:
        template@presets?str: templates/run-ctr.yml

tools:
  workflow:
  - name: local

renderers:
- env:
    enable_exec: true

  file:presets:
    alias: presets

- tpl:
    include:
    - path: templates/run-ctr.yml

workflow:run:
- name: test
  matrix:
    preset:
    - golang
    - buildah
    - tools
  jobs:
  - task:
      ref@tpl: workflow:run(test-{{ matrix.preset }})
      matrix_filter: {}

- name: report
- name: tidy
- name: lint
  matrix:
    include:
    - tool: [editorconfig-checker]
      # version: ["2.4"]
      # workdir: [""]
      config:
      - __@presets#cached-file: tools/editorconfig-checker/config.json

    # TODO
    - tool: [shellcheck]
      # version: [""]
      # workdir: [""]

    - tool: [yamllint]
      # version: ["1.26"]
      # workdir: [""]
      # TODO: merge yamllint config for this repo
      # config:
      # - __@presets#cached-file: tools/yamllint/config.yaml

    - tool: [golangci-lint]
      # version: ["1.45"]
      # workdir: [""]
      # config: [""]
      # pkgs: ["./..."]

      workdir:
      - __@tpl: |-
          {{- fs.Join dukkha.WorkDir "golang/testdata" -}}
      config: ["../../tools/testdata/golangci-lint.yml"]

  jobs:
  - cmd@presets|tpl#use-spec: tools/presets.tpl
    chdir@tpl: |-
      {{- matrix.workdir | default "" -}}
