name: artifacts

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      os:
        required: false
        default: ubuntu-latest
        type: string

      go-version:
        required: false
        default: "1.17.x"
        type: string

      release:
        required: true
        description: |-
          Create a new release
        type: boolean
        default: false

      prepare:
        required: false
        default: ""
        type: string

    secrets:
      token:
        description: |-
          github token
        required: true

      cosign-private-key:
        required: true

      cosign-private-key-password:
        required: true

env:
  GO111MODULE: "on"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        # disable shallow-clone
        fetch-depth: 0

    - name: Install cosign
      uses: sigstore/cosign-installer@v1.3.1

    - name: Install dukkha
      uses: arhat-dev/actions-setup-dukkha@master
      with:
        version: latest
        go-version: ${{ inputs.go-version }}

    - name: Prepare artifacts build
      run: |-
        ${{ inputs.prepare }}

    - name: Build artifacts
      run: |-
        dukkha run workflow local run build-artifacts

    - name: Sign artifacts
      env:
        # common private key env for cosign
        COSIGN_PRIVATE_KEY: ${{ secrets.cosign-private-key }}
        COSIGN_PRIVATE_KEY_PASSWORD: ${{ secrets.cosign-private-key-password }}
      run: |-
        dukkha run workflow local run sign-artifacts

    - name: Upload artifacts
      env:
        # common user pass env for ghcr login
        GHCR_USER: ${{ github.actor }}
        GHCR_PASS: ${{ secrets.token }}
        # common private key env for cosign
        COSIGN_PRIVATE_KEY: ${{ secrets.cosign-private-key }}
        COSIGN_PRIVATE_KEY_PASSWORD: ${{ secrets.cosign-private-key-password }}
      run: |-
        dukkha run workflow local run upload-artifacts

    - name: Create Release
      if: inputs.release
      env:
        # GH_TOKEN env is required by github cli (gh)
        GH_TOKEN: ${{ secrets.token }}
      run: |
        dukkha run workflow local run create-release
