name: artifacts

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      fail-fast:
        required: false
        type: boolean
        default: false

      matrix:
        required: false
        type: string
        default: |-
          {
            "os": ["ubuntu-latest"],
            "go": ["1.18.x"]
          }

      release:
        required: true
        description: |-
          Create a new release
        type: boolean
        default: false

      prepare:
        required: false
        default: ""
        type: string

      install_dukkha:
        required: false
        default: true
        type: boolean

    secrets:
      token:
        description: |-
          github token
        required: true

      cosign-private-key:
        required: true

      cosign-private-key-password:
        required: true

env:
  GO111MODULE: "on"

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: ${{ inputs.fail-fast }}
      matrix: ${{ fromJson(inputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        # disable shallow-clone
        fetch-depth: 0

    - name: Install cosign
      uses: sigstore/cosign-installer@v2.4.1

    - name: Install dukkha
      if: inputs.install_dukkha
      uses: arhat-dev/actions-setup-dukkha@master
      with:
        version: latest
        go-version: ${{ matrix.go }}

    - name: Install go
      if: ${{ ! inputs.install_dukkha }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Prepare artifacts build
      run: |-
        ${{ inputs.prepare }}

    - name: Build artifacts
      run: |-
        dukkha run workflow local run build-artifacts

    - name: Sign artifacts
      env:
        # common private key env for cosign
        COSIGN_PRIVATE_KEY: ${{ secrets.cosign-private-key }}
        COSIGN_PRIVATE_KEY_PASSWORD: ${{ secrets.cosign-private-key-password }}
      run: |-
        dukkha run workflow local run sign-artifacts

    - name: Upload artifacts
      env:
        # common user pass env for ghcr login
        GHCR_USER: ${{ github.actor }}
        GHCR_PASS: ${{ secrets.token }}
        # common private key env for cosign
        COSIGN_PRIVATE_KEY: ${{ secrets.cosign-private-key }}
        COSIGN_PRIVATE_KEY_PASSWORD: ${{ secrets.cosign-private-key-password }}
      run: |-
        dukkha run workflow local run upload-artifacts

    - name: Create Release
      if: inputs.release
      env:
        # GH_TOKEN env is required by github cli (gh)
        GH_TOKEN: ${{ secrets.token }}
      run: |
        dukkha run workflow local run create-release
