name: CI

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      reason:
        description: reason to run this workflow
        required: false
        default: test

  pull_request:
    branches:
    - master

  push:
    branches:
    - master
    tags:
    - v*

jobs:
  stylecheck:
    uses: arhat-dev/dukkha-presets/.github/workflows/stylecheck.yml@master
  test:
    uses: arhat-dev/dukkha-presets/.github/workflows/test.yml@master
    with:
      matrix: |-
        {
          "os": [
            "macos-latest",
            "windows-latest",
            "ubuntu-latest"
          ],
          "go": [
            "1.18.x"
          ]
        }
      install_wine: true
