name: image

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      go-version:
        required: false
        default: "1.17.x"
        type: string

    secrets:
      token:
        description: |-
          github token
        required: true

      # TODO: support cosign image signing in pipeline
      cosign-private-key:
        required: false

      cosign-private-key-password:
        required: false

env:
  GO111MODULE: "on"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # disable shallow-clone
        fetch-depth: 0

    - name: Install cosign
      uses: sigstore/cosign-installer@v1.3.1

    - name: Install dukkha
      uses: arhat-dev/actions-setup-dukkha@master
      with:
        version: latest
        go-version: ${{ inputs.go-version }}

    - name: Setup multi-arch support
      uses: dbhi/qus/action@main

    - name: Build images
      run: |-
        dukkha run workflow local run build-images

    - name: Sign images
      env:
        COSIGN_PRIVATE_KEY: ${{ secrets.cosign-private-key }}
        COSIGN_PRIVATE_KEY_PASSWORD: ${{ secrets.cosign-private-key-password }}
      run: |-
        dukkha run workflow local run sign-images

    - name: Inspect images
      if: always()
      run: |-
        podman images
        docker images

    - name: Push images
      env:
        GHCR_USER: ${{ github.actor }}
        GHCR_PASS: ${{ secrets.token }}
      run: |-
        dukkha run workflow local run push-images
